export function Privacy() {
  return (
    <article className="legal-page">
      <h1>Privacy policy</h1>
      <p className="updated">Last updated: September 26, 2026</p>

      <p>
        This policy describes how YCal approaches privacy. The YCal mobile application (the
        &quot;App&quot;) is an independent, free client for Yahoo Calendar over standard CalDAV
        protocols, with an optional paid Premium upgrade. It is not affiliated with, endorsed by, or
        officially supported by Yahoo, Verizon Media, or Google.
      </p>

      <h2>Your calendar data never touches our servers</h2>
      <p>
        YCal does not run a backend that receives, stores, or has access to your Yahoo account
        credentials, calendars, or events. There is no YCal cloud database for your calendar data and
        no YCal user account system. Calendar sync and sign-in traffic go directly between your device
        and Yahoo&apos;s services (or other CalDAV services you configure, if applicable) &mdash; never
        through a YCal-operated intermediary. Yahoo hosts your account and calendar data and sets the
        rules for that processing; review Yahoo&apos;s own privacy policy and terms when you use their
        services.
      </p>

      <h2>What stays on your device</h2>
      <p>
        To work offline and avoid signing in every launch, the App stores your Yahoo sign-in details
        (email and app password) in the device&apos;s secure, encrypted credential storage, and keeps a
        local cache of your synced calendars, events, and attendee addresses in a local database on the
        device. Reminders are scheduled as local notifications on your device; no reminder or event data
        is sent to a push-notification server to make that happen. This data remains on your phone or
        tablet unless you remove the App, remove an account, or use the in-app sign-out and
        data-clearing options.
      </p>

      <h2>Limited backend services we operate</h2>
      <p>
        Calendar data itself never touches our servers, as described above. We do operate a small
        backend, hosted on cloud infrastructure in the United States, for two narrow, account-adjacent
        purposes described below. Neither of these services ever receives your calendar events,
        attendees, or Yahoo app password, and neither is sold, shared with advertisers, or used for
        advertising identifiers.
      </p>
      <p>
        <strong>Purchase verification.</strong> YCal offers an optional, auto-renewing Premium
        subscription (monthly or yearly), billed and processed entirely by Google Play Billing. We never
        see or store your payment card, bank, or billing address details &mdash; Google handles that as
        the payment processor. To confirm and remember that a purchase is genuine and still active (for
        example, after you reinstall the App or switch devices), we store a random installation
        identifier generated by the App, the subscription product purchased, and the purchase token,
        status, and expiry date that Google Play itself provides. This record is kept for as long as
        needed to administer your subscription.
      </p>
      <p>
        <strong>Account contact sync.</strong> When you sign in to a calendar account in the App, YCal
        also sends the sign-in email address(es) for your signed-in account(s), the same random
        installation identifier, and coarse device information (locale, timezone, device model, OS
        version, and app version &mdash; no GPS or precise location) to that same backend. This applies
        whether or not you use Premium. We use this so we can reach registered users with important
        account, subscription, or product communications, and to understand basic app usage across
        devices. This is separate from your device&apos;s address book &mdash; YCal does not request or
        read your contacts list. These records are kept for as long as your account remains in active
        use, or until you ask us to delete them.
      </p>

      <h2>App permissions</h2>
      <p>
        YCal requests device permissions needed to show reminder notifications, keep calendars synced in
        the background, and process Google Play purchases. It does not request access to your device
        contacts list, location, camera, or photo library, and it does not use advertising identifiers.
      </p>

      <h2>This website</h2>
      <p>
        This site is a static marketing page (built with standard web tooling). It does not embed
        sign-in, forms, analytics, or advertising trackers in the published code. Your browser still
        connects to whichever host serves the files (for example GitHub Pages or another static host);
        that provider may process routine technical data such as IP address and access logs under its
        own policies, which we do not control.
      </p>

      <h2>Children&apos;s privacy</h2>
      <p>
        YCal is not directed at children and we do not knowingly collect personal information from
        children. Signing in requires a Yahoo account and app password, which are subject to Yahoo&apos;s
        own age requirements.
      </p>

      <h2>Your choices</h2>
      <p>
        You can remove a signed-in account or sign out entirely from within the App to clear locally
        cached credentials, calendar data, and pending reminders. Uninstalling the App removes all data
        stored on your device. To request deletion of a subscription-verification record, contact us
        with your Google Play order/receipt information so we can locate it &mdash; we have no name or
        email tied to that record otherwise. To request deletion of an account-contact sync record,
        email us from (or naming) the sign-in address you used, and we will remove it.
      </p>

      <h2>Contact</h2>
      <p>
        For privacy questions or data requests, email{' '}
        <a href="mailto:ycal.developer@gmail.com">ycal.developer@gmail.com</a>.
      </p>

      <h2>Changes</h2>
      <p>We may update this policy occasionally. The &quot;Last updated&quot; date will change when we do.</p>
    </article>
  )
}
